twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        useragents: '@App\Twig\Extension\UserAgentExtension'
        version: '%version%'
        config: '@App\Configuration\Configuration'
        trackingConfig: '@App\Tracking\MatomoConfig'

when@test:
    twig:
        strict_variables: true
