services:
  webserver:
    build: ./docker/nginx
    container_name: wsa_publicserver
    working_dir: /var/www/project
    volumes:
      - ./public:/var/www/project/public
      - ./docker/nginx/config/vhost.conf:/etc/nginx/conf.d/default.conf #Überschreibt die config für die Entwicklung
    ports:
      - "8985:80"
      - "8986:443"
    depends_on:
      - php

  php:
    build: ./docker/php-fpm
    container_name: wsa_publicphp
    working_dir: /var/www/project
    environment:
      - APPLICATION_ENV=dev
      - PHP_IDE_CONFIG=serverName=_
      - APP_DEBUG=true
    volumes:
      - ./:/var/www/project
      - ./docker/php-fpm/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini #Überschreibt die config für die Entwicklung
      - ./docker/php-fpm/config/development.ini:/usr/local/etc/php/php.ini #Überschreibt die config für die Entwicklung

    expose:
      - 9090


#volumes:
####> doctrine/doctrine-bundle ###
#  database_data:
###< doctrine/doctrine-bundle ###
  mysql:
    image: mysql:latest
    container_name: wsa_publicmysql
    working_dir: /var/www/project
    command: --max_allowed_packet=10000000000
    volumes:
      - ./docker/data/mysql2:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wsa
      - MYSQL_USER=wsa
      - MYSQL_PASSWORD=wsa
    ports:
      - 13306:3306
