services:
  webserver:
    build:
      dockerfile: docker/nginx/prod/Dockerfile
    pull_policy: always
    container_name: wsa-server
    working_dir: /var/www/project
    volumes:
      - ./public:/var/www/project/public
      - ./docker/nginx/config/vhost.prod.conf:/etc/nginx/conf.d/default.conf #Überschreibt die config für die Entwicklung
      - ./docker/nginx/certs:/etc/nginx/certs
    ports:
      - "18999:80"
    depends_on:
      - php

  php:
    build:
      dockerfile: docker/php-fpm/prod/Dockerfile
    pull_policy: always
    container_name: wsa-php
    working_dir: /var/www/project
    env_file:
      - .env.prod
    volumes:
      - ./:/var/www/project
      - ./docker/php-fpm/prod/config/production.ini:/usr/local/etc/php/php.ini

