parameters:
  matomo_enabled: '%env(bool:MATOMO_ENABLED)%'
  matomo_server_side: '%env(bool:MATOMO_SERVER_SIDE)%'
  matomo_cookie_domain: '%env(MATOMO_COOKE_DOMAIN)%'
  matomo_noscript_img: '%env(string:MATOMO_NO_SCRIPT_IMG)%'
  matomo_tracker_url: '%env(MATOMO_TRACKER_URL)%'
  matomo_domain: '%env(MATOMO_DOMAIN)%'
